#include "calibration.h"
#include <stdio.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979
#endif

static void g92_reset(FILE *f) { fprintf(f, "G92 E0 ; reset extruder\n"); }

static void retract(FILE *f, float *e, float retract_mm, float travel_speed) {
    if (retract_mm > 0) { fprintf(f, "G1 E-%.3f F%.0f ; retract\n", retract_mm, travel_speed * 60); *e -= retract_mm; }
}

static void unretract(FILE *f, float *e, float retract_mm, float print_speed) {
    if (retract_mm > 0) { fprintf(f, "G1 E+%.3f F%.0f ; unretract\n", retract_mm, print_speed * 60); *e += retract_mm; }
}

static float vol_cross(float filament_dia) {
    return (float)(M_PI * (filament_dia / 2.0) * (filament_dia / 2.0));
}

static void extruder_move(FILE *f, float *e, float x, float y, float ex, float ey,
                          float line_w, float layer_h, float filament_dia, float speed, int first) {
    float L = sqrtf((x - ex) * (x - ex) + (y - ey) * (y - ey));
    float vol = L * line_w * layer_h;
    float de = vol / vol_cross(filament_dia);
    *e += de;
    if (first) fprintf(f, "G1 X%.3f Y%.3f E%.4f F%.0f\n", x, y, *e, speed * 60);
    else fprintf(f, "G1 X%.3f Y%.3f E%.4f\n", x, y, *e);
}

static void travel(FILE *f, float *e, float x, float y, float retract_mm, float travel_speed) {
    retract(f, e, retract_mm, travel_speed);
    fprintf(f, "G0 X%.3f Y%.3f F%.0f ; travel\n", x, y, travel_speed * 60);
}

static void emit_header(FILE *f, float bed_temp, int nozzle_temp, const char *type) {
    fprintf(f, "; Calibration: %s (generated by Volt360)\n", type);
    fprintf(f, "M140 S%d\nM190 S%d\n", (int)bed_temp, (int)bed_temp);
    fprintf(f, "M104 S%d\nM109 S%d\n", nozzle_temp, nozzle_temp);
    fprintf(f, "G28 ; home\n");
}

static void emit_footer(FILE *f, float retract_mm, float travel_speed, float *e) {
    retract(f, e, retract_mm, travel_speed);
    fprintf(f, "M104 S0 ; hotend off\nM140 S0 ; bed off\nG0 X0 Y200 F%.0f ; present\nM84 ; motors off\n", travel_speed * 60);
}

// ================= temperature tower =================
bool calib_temp_tower(const char *path, float bed_temp, int temp_min, int temp_max, int temp_step,
                      float layer_h, float line_w, float print_speed, float travel_speed,
                      float retract_mm, float filament_dia) {
    if (!path || temp_step <= 0 || temp_max <= temp_min) return false;
    FILE *f = fopen(path, "w");
    if (!f) return false;
    emit_header(f, bed_temp, temp_min, "Temperature Tower");
    float e = 0;
    float sx = 100, sy = 100; // tower center
    float hw = 10, hd = 10; // tower half-size
    float z = layer_h;
    int num_levels = (temp_max - temp_min) / temp_step + 1;
    float level_height = 10; // mm per temp level
    int layers_per_level = (int)(level_height / layer_h + 0.5f);
    if (layers_per_level < 1) layers_per_level = 1;

    for (int lvl = 0; lvl < num_levels; lvl++) {
        int t = temp_min + lvl * temp_step;
        if (lvl > 0) { fprintf(f, "M104 S%d\nM109 S%d\n", t, t); }
        for (int li = 0; li < layers_per_level; li++) {
            fprintf(f, "; temp=%d layer=%d\n", t, li);
            fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
            g92_reset(f); e = 0;
            travel(f, &e, sx - hw, sy - hd, retract_mm, travel_speed);
            unretract(f, &e, retract_mm, print_speed);
            // perimeters
            for (int wall = 0; wall < 2; wall++) {
                float cx = sx - hw + wall * line_w, cy = sy - hd + wall * line_w;
                float cw = hw * 2 - wall * line_w * 2, cd = hd * 2 - wall * line_w * 2;
                if (cw <= 0 || cd <= 0) break;
                extruder_move(f, &e, cx, cy, cx, cy, line_w, layer_h, filament_dia, print_speed, 1);
                extruder_move(f, &e, cx + cw, cy, cx, cy, line_w, layer_h, filament_dia, print_speed, 0);
                extruder_move(f, &e, cx + cw, cy + cd, cx + cw, cy, line_w, layer_h, filament_dia, print_speed, 0);
                extruder_move(f, &e, cx, cy + cd, cx + cw, cy + cd, line_w, layer_h, filament_dia, print_speed, 0);
                extruder_move(f, &e, cx, cy, cx, cy + cd, line_w, layer_h, filament_dia, print_speed, 0);
            }
            z += layer_h;
        }
    }
    emit_footer(f, retract_mm, travel_speed, &e);
    fclose(f);
    return true;
}

// ================= flow rate =================
bool calib_flow_rate(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                     float line_w, float print_speed, float travel_speed, float retract_mm,
                     float filament_dia, float mult_min, float mult_max, float mult_step) {
    if (!path || mult_step <= 0 || mult_max <= mult_min) return false;
    FILE *f = fopen(path, "w");
    if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Flow Rate Calibration");
    float e = 0, z = layer_h;
    float sx = 50, sy = 100, sq = 20; // square size
    float cx = sx, cy = sy;
    int num = (int)((mult_max - mult_min) / mult_step) + 1;

    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);

    for (int i = 0; i < num; i++) {
        float mult = mult_min + i * mult_step;
        float mw = line_w * mult;
        float px = cx + (float)(i % 3) * (sq + 10);
        float py = cy - (float)(i / 3) * (sq + 10);
        fprintf(f, "; square %d flow=%.0f%%\n", i, mult * 100);
        g92_reset(f); e = 0;
        travel(f, &e, px, py, retract_mm, travel_speed);
        unretract(f, &e, retract_mm, print_speed);
        // single line outline (solid infill for top surface)
        extruder_move(f, &e, px, py, px, py, mw, layer_h, filament_dia, print_speed, 1);
        extruder_move(f, &e, px + sq, py, px, py, mw, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, px + sq, py + sq, px + sq, py, mw, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, px, py + sq, px + sq, py + sq, mw, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, px, py, px, py + sq, mw, layer_h, filament_dia, print_speed, 0);
        // infill
        float step = mw * 0.95f;
        for (float yy = py + step; yy < py + sq; yy += step) {
            extruder_move(f, &e, px, yy, px + sq, yy, mw, layer_h, filament_dia, print_speed, 0);
        }
    }
    emit_footer(f, retract_mm, travel_speed, &e);
    fclose(f);
    return true;
}

// ================= pressure advance =================
bool calib_pressure_advance(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                            float line_w, float print_speed, float travel_speed, float retract_mm,
                            float filament_dia, float pa_min, float pa_max, float pa_step,
                            bool klipper) {
    if (!path || pa_step <= 0 || pa_max <= pa_min) return false;
    FILE *f = fopen(path, "w");
    if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Pressure Advance Pattern");
    float e = 0, z = layer_h;
    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
    float px = 50, py = 150;
    int num = (int)((pa_max - pa_min) / pa_step) + 1;

    for (int i = 0; i < num; i++) {
        float pa = pa_min + i * pa_step;
        float lx = px, ly = py - i * 12;
        int l = 80; // line length
        if (klipper)
            fprintf(f, "SET_PRESSURE_ADVANCE ADVANCE=%.4f\n", pa);
        else
            fprintf(f, "M900 K%.2f\n", pa);
        fprintf(f, "; PA=%.4f\n", pa);
        g92_reset(f); e = 0;
        travel(f, &e, lx, ly, retract_mm, travel_speed);
        unretract(f, &e, retract_mm, print_speed);
        // fast line (test corner sharpness at speed)
        extruder_move(f, &e, lx + l, ly, lx, ly, line_w, layer_h, filament_dia, print_speed, 1);
        // slow line (reference)
        extruder_move(f, &e, lx, ly + 2, lx + l, ly + 2, line_w, layer_h, filament_dia, print_speed * 0.5f, 0);
    }
    emit_footer(f, retract_mm, travel_speed, &e);
    fclose(f);
    return true;
}

// ================= max volumetric flow =================
bool calib_max_flow(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                    float line_w, float speed_min, float speed_max, float speed_step,
                    float travel_speed, float retract_mm, float filament_dia) {
    if (!path || speed_step <= 0 || speed_max <= speed_min) return false;
    FILE *f = fopen(path, "w");
    if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Max Flow Test");
    float e = 0, z = layer_h;
    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
    float px = 50, py = 100, l = 100;
    int num = (int)((speed_max - speed_min) / speed_step) + 1;

    for (int i = 0; i < num; i++) {
        float spd = speed_min + i * speed_step;
        float ly = py - i * 6;
        fprintf(f, "; speed=%.0fmm/s\n", spd);
        g92_reset(f); e = 0;
        travel(f, &e, px, ly, retract_mm, travel_speed);
        unretract(f, &e, retract_mm, spd);
        extruder_move(f, &e, px + l, ly, px, ly, line_w, layer_h, filament_dia, spd, 1);
    }
    emit_footer(f, retract_mm, travel_speed, &e);
    fclose(f);
    return true;
}

// ================= VFA tower =================
bool calib_vfa_tower(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                     float line_w, float speed_min, float speed_max, float speed_step,
                     float travel_speed, float retract_mm, float filament_dia,
                     float tower_w, float tower_d, float z_height) {
    if (!path || speed_step <= 0) return false;
    FILE *f = fopen(path, "w");
    if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "VFA Tower");
    float e = 0;
    float cx = 150, cy = 150;
    float hw = tower_w * 0.5f, hd = tower_d * 0.5f;
    float z = layer_h;
    int num_speeds = (int)((speed_max - speed_min) / speed_step) + 1;
    float band_h = z_height / (float)num_speeds;
    int layers_per = (int)(band_h / layer_h + 0.5f);
    if (layers_per < 1) layers_per = 1;

    for (int s = 0; s < num_speeds; s++) {
        float spd = speed_min + s * speed_step;
        for (int li = 0; li < layers_per; li++) {
            fprintf(f, "; VFA speed=%.0f z=%.3f\n", spd, z);
            fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
            g92_reset(f); e = 0;
            travel(f, &e, cx - hw, cy - hd, retract_mm, travel_speed);
            unretract(f, &e, retract_mm, spd);
            extruder_move(f, &e, cx - hw, cy - hd, cx - hw, cy - hd, line_w, layer_h, filament_dia, spd, 1);
            extruder_move(f, &e, cx + hw, cy - hd, cx - hw, cy - hd, line_w, layer_h, filament_dia, spd, 0);
            extruder_move(f, &e, cx + hw, cy + hd, cx + hw, cy - hd, line_w, layer_h, filament_dia, spd, 0);
            extruder_move(f, &e, cx - hw, cy + hd, cx + hw, cy + hd, line_w, layer_h, filament_dia, spd, 0);
            extruder_move(f, &e, cx - hw, cy - hd, cx - hw, cy + hd, line_w, layer_h, filament_dia, spd, 0);
            z += layer_h;
        }
    }
    emit_footer(f, retract_mm, travel_speed, &e);
    fclose(f);
    return true;
}

// ================= input shaper calibration =================
bool calib_input_shaper(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                        float line_w, float print_speed, float travel_speed, float retract_mm,
                        float filament_dia, float freq_min, float freq_max, float freq_step,
                        float tower_w, float tower_d, float z_height) {
    if (!path || freq_step <= 0 || freq_max <= freq_min) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Input Shaper Calibration");
    float e = 0;
    float cx = 150, cy = 150;
    float hw = tower_w * 0.5f, hd = tower_d * 0.5f;
    float z = layer_h;
    int num_freqs = (int)((freq_max - freq_min) / freq_step) + 1;
    float band_h = z_height / (float)num_freqs;
    int layers_per = (int)(band_h / layer_h + 0.5f);
    if (layers_per < 1) layers_per = 1;

    for (int s = 0; s < num_freqs; s++) {
        float freq = freq_min + s * freq_step;
        fprintf(f, "SET_INPUT_SHAPER SHAPER_FREQ_X=%.1f SHAPER_FREQ_Y=%.1f SHAPER_TYPE=zv\n", freq, freq);
        for (int li = 0; li < layers_per; li++) {
            fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
            g92_reset(f); e = 0;
            travel(f, &e, cx - hw, cy - hd, retract_mm, travel_speed);
            unretract(f, &e, retract_mm, print_speed);
            for (int wall = 0; wall < 2; wall++) {
                float wx = cx - hw + wall * line_w, wy = cy - hd + wall * line_w;
                float ww = hw * 2 - wall * line_w * 2, wd = hd * 2 - wall * line_w * 2;
                if (ww <= 0 || wd <= 0) break;
                extruder_move(f, &e, wx, wy, wx, wy, line_w, layer_h, filament_dia, print_speed, 1);
                extruder_move(f, &e, wx + ww, wy, wx, wy, line_w, layer_h, filament_dia, print_speed, 0);
                extruder_move(f, &e, wx + ww, wy + wd, wx + ww, wy, line_w, layer_h, filament_dia, print_speed, 0);
                extruder_move(f, &e, wx, wy + wd, wx + ww, wy + wd, line_w, layer_h, filament_dia, print_speed, 0);
                extruder_move(f, &e, wx, wy, wx, wy + wd, line_w, layer_h, filament_dia, print_speed, 0);
            }
            z += layer_h;
        }
        travel(f, &e, cx - hw - 5, cy - hd - 2, retract_mm, travel_speed);
        unretract(f, &e, retract_mm, print_speed);
        extruder_move(f, &e, cx + hw + 5, cy - hd - 2, cx - hw - 5, cy - hd - 2, line_w, layer_h, filament_dia, print_speed, 1);
    }
    fprintf(f, "SET_INPUT_SHAPER SHAPER_FREQ_X=0 SHAPER_FREQ_Y=0\n");
    emit_footer(f, retract_mm, travel_speed, &e);
    fclose(f); return true;
}

// ================= auto-arrange (2D shelf packing) =================
int calib_auto_arrange(int count, float *sizes_x, float *sizes_y,
                       float plate_x, float plate_y, float spacing,
                       float *out_x, float *out_y) {
    if (count <= 0 || !sizes_x || !sizes_y || !out_x || !out_y) return 0;
    int *order = (int *)malloc(sizeof(int) * (size_t)count);
    float *keys = (float *)malloc(sizeof(float) * (size_t)count);
    for (int i = 0; i < count; i++) { order[i] = i; keys[i] = sizes_y[i] > sizes_x[i] ? sizes_y[i] : sizes_x[i]; }
    for (int i = 0; i < count; i++)
        for (int j = i + 1; j < count; j++)
            if (keys[order[j]] > keys[order[i]]) { int t = order[i]; order[i] = order[j]; order[j] = t; }

    float shelf_y = 0, shelf_h = 0, shelf_x = 0;
    int placed = 0;
    for (int si = 0; si < count; si++) {
        int idx = order[si];
        float sx = sizes_x[idx] + spacing, sy = sizes_y[idx] + spacing;
        if (sx > plate_x || sy > plate_y) continue;
        if (shelf_x + sx <= plate_x && sy <= shelf_h) {
            out_x[idx] = spacing + shelf_x;
            out_y[idx] = spacing + shelf_y;
            shelf_x += sx; placed++; continue;
        }
        float new_y = shelf_y + shelf_h + spacing;
        if (new_y + sy > plate_y) break;
        shelf_y = new_y; shelf_h = sy; shelf_x = sx;
        out_x[idx] = spacing; out_y[idx] = spacing + shelf_y; placed++;
    }
    free(order); free(keys);
    return placed;
}

// ================= auto-orient =================
bool calib_auto_orient(CadMesh *mesh, float *out_rx, float *out_ry, float *out_rz) {
    if (!mesh || !mesh->valid || mesh->ntris < 1) return false;
    // Find the face with the largest projected area on XY.
    // For each triangle, compute area. The orientation with the face normal
    // pointing to +Z gives largest XY projection = cos(angle) * area.
    // So the face with largest area that points roughly -Z is the best base.
    float best_area = 0; V3 best_n = v3(0, 0, -1);
    for (int t = 0; t < mesh->ntris; t++) {
        int i0 = mesh->idx[t * 3 + 0], i1 = mesh->idx[t * 3 + 1], i2 = mesh->idx[t * 3 + 2];
        V3 p0 = v3(mesh->pos[i0 * 3], mesh->pos[i0 * 3 + 1], mesh->pos[i0 * 3 + 2]);
        V3 p1 = v3(mesh->pos[i1 * 3], mesh->pos[i1 * 3 + 1], mesh->pos[i1 * 3 + 2]);
        V3 p2 = v3(mesh->pos[i2 * 3], mesh->pos[i2 * 3 + 1], mesh->pos[i2 * 3 + 2]);
        V3 e1 = v3(p1.x - p0.x, p1.y - p0.y, p1.z - p0.z);
        V3 e2 = v3(p2.x - p0.x, p2.y - p0.y, p2.z - p0.z);
        V3 n = v3(e1.y * e2.z - e1.z * e2.y, e1.z * e2.x - e1.x * e2.z, e1.x * e2.y - e1.y * e2.x);
        float area = sqrtf(n.x * n.x + n.y * n.y + n.z * n.z) * 0.5f;
        // normalize
        if (area > 1e-6f) { n.x /= (area * 2); n.y /= (area * 2); n.z /= (area * 2); }
        // prefer faces whose normal has a negative Z component (face pointing downward)
        if (area > best_area && n.z < -0.1f) { best_area = area; best_n = n; }
    }
    // If no downward face found, use largest face regardless
    if (best_area < 1e-6f) {
        for (int t = 0; t < mesh->ntris; t++) {
            int i0 = mesh->idx[t * 3 + 0], i1 = mesh->idx[t * 3 + 1], i2 = mesh->idx[t * 3 + 2];
            V3 p0 = v3(mesh->pos[i0 * 3], mesh->pos[i0 * 3 + 1], mesh->pos[i0 * 3 + 2]);
            V3 p1 = v3(mesh->pos[i1 * 3], mesh->pos[i1 * 3 + 1], mesh->pos[i1 * 3 + 2]);
            V3 p2 = v3(mesh->pos[i2 * 3], mesh->pos[i2 * 3 + 1], mesh->pos[i2 * 3 + 2]);
            V3 e1 = v3(p1.x - p0.x, p1.y - p0.y, p1.z - p0.z);
            V3 e2 = v3(p2.x - p0.x, p2.y - p0.y, p2.z - p0.z);
            V3 n = v3(e1.y * e2.z - e1.z * e2.y, e1.z * e2.x - e1.x * e2.z, e1.x * e2.y - e1.y * e2.x);
            float area = sqrtf(n.x * n.x + n.y * n.y + n.z * n.z) * 0.5f;
            if (area > best_area) { best_area = area; if (area > 1e-6f) { best_n.x = n.x/(area*2); best_n.y = n.y/(area*2); best_n.z = n.z/(area*2); } }
        }
    }
    if (best_area < 1e-6f) return false;
    // Compute rotation to align best_n with (0,0,-1) — the downward face normal
    // We want to rotate so that best_n aligns with -Z axis
    // Rotation axis = cross(best_n, (0,0,-1)), angle = acos(dot(best_n, (0,0,-1)))
    V3 target = v3(0, 0, -1);
    float dot = best_n.x * target.x + best_n.y * target.y + best_n.z * target.z;
    if (dot > 0.99f) { *out_rx = 0; *out_ry = 0; *out_rz = 0; return true; }
    if (dot < -0.99f) { *out_rx = 180; *out_ry = 0; *out_rz = 0; return true; }
    float angle = acosf(dot);
    V3 axis = v3(best_n.y * target.z - best_n.z * target.y,
                 best_n.z * target.x - best_n.x * target.z,
                 best_n.x * target.y - best_n.y * target.x);
    float alen = sqrtf(axis.x * axis.x + axis.y * axis.y + axis.z * axis.z);
    if (alen < 1e-6f) { *out_rx = *out_ry = *out_rz = 0; return true; }
    axis.x /= alen; axis.y /= alen; axis.z /= alen;
    // Decompose the rotation into Euler angles (ZYX order, roughly)
    // Simple: project to get rx/ry/rz
    *out_rx = axis.x * angle * 180.0f / (float)M_PI;
    *out_ry = axis.y * angle * 180.0f / (float)M_PI;
    *out_rz = axis.z * angle * 180.0f / (float)M_PI;
    return true;
}

// ================= additional calibration tests =================

bool calib_retraction(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                      float line_w, float print_speed, float travel_speed, float filament_dia,
                      float ret_min, float ret_max, float ret_step) {
    if (!path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Retraction Test");
    float e = 0, z = layer_h;
    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
    float px = 100, py = 150;
    int n = (int)((ret_max - ret_min) / ret_step) + 1;
    for (int i = 0; i < n; i++) {
        float ret = ret_min + i * ret_step;
        fprintf(f, "; retract=%.2fmm\n", ret);
        g92_reset(f); e = 0;
        travel(f, &e, px, py - i * 8, ret, travel_speed);
        unretract(f, &e, ret, print_speed);
        extruder_move(f, &e, px + 40, py - i * 8, px, py - i * 8, line_w, layer_h, filament_dia, print_speed, 1);
        retract(f, &e, ret, travel_speed);
    }
    emit_footer(f, 0, travel_speed, &e); fclose(f); return true;
}

bool calib_bridge(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                  float line_w, float print_speed, float travel_speed,
                  float filament_dia, float bridge_len_mm) {
    if (!path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Bridge Test");
    float e = 0, z = layer_h;
    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
    // print two anchor blocks then bridge between them
    float ax = 100, ay = 120;
    g92_reset(f); e = 0;
    for (int bi = 0; bi < 2; bi++) {
        float bx = ax + bi * (bridge_len_mm + 10);
        travel(f, &e, bx, ay, 0, travel_speed);
        unretract(f, &e, 0, print_speed);
        extruder_move(f, &e, bx, ay, bx + 5, ay + 5, line_w, layer_h, filament_dia, print_speed, 1);
        extruder_move(f, &e, bx + 5, ay, bx + 5, ay + 25, line_w, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, bx, ay + 25, bx + 5, ay + 25, line_w, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, bx, ay, bx, ay + 25, line_w, layer_h, filament_dia, print_speed, 0);
    }
    // bridge
    travel(f, &e, ax + 5, ay + 15, 0, travel_speed);
    unretract(f, &e, 0, print_speed);
    extruder_move(f, &e, ax + 5, ay + 15, ax + 5 + bridge_len_mm, ay + 5, line_w, layer_h, filament_dia, print_speed, 1);
    emit_footer(f, 0, travel_speed, &e); fclose(f); return true;
}

bool calib_tolerance(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                     float line_w, float print_speed, float travel_speed,
                     float filament_dia, float clearance_min, float clearance_max) {
    if (!path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Tolerance Test");
    float e = 0, z = layer_h;
    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
    float px = 80, py = 100;
    int n = 6;
    for (int i = 0; i < n; i++) {
        g92_reset(f); e = 0;
        float s = clearance_min + i * (clearance_max - clearance_min) / (float)n;
        float bx = px + i * 22, by = py;
        travel(f, &e, bx, by, 0, travel_speed);
        unretract(f, &e, 0, print_speed);
        extruder_move(f, &e, bx, by, bx + s, by, line_w, layer_h, filament_dia, print_speed, 1);
        extruder_move(f, &e, bx + s, by, bx + s, by + s, line_w, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, bx, by + s, bx + s, by + s, line_w, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, bx, by, bx, by + s, line_w, layer_h, filament_dia, print_speed, 0);
    }
    emit_footer(f, 0, travel_speed, &e); fclose(f); return true;
}

bool calib_overhang(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                    float line_w, float print_speed, float travel_speed, float filament_dia) {
    if (!path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Overhang Test");
    float e = 0, z = layer_h;
    float px = 80, py = 120;
    // print L-shaped overhangs at increasing angles
    for (int i = 0; i < 8; i++) {
        z = layer_h * (float)(i + 1);
        fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
        float over = (float)(i + 1) * 2.0f;
        g92_reset(f); e = 0;
        travel(f, &e, px + i * 20, py, 0, travel_speed);
        unretract(f, &e, 0, print_speed);
        extruder_move(f, &e, px + i * 20, py, px + i * 20 + over, py, line_w, layer_h, filament_dia, print_speed, 1);
        extruder_move(f, &e, px + i * 20 + over, py, px + i * 20 + over, py - 5, line_w, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, px + i * 20, py - 5, px + i * 20 + over, py - 5, line_w, layer_h, filament_dia, print_speed, 0);
        extruder_move(f, &e, px + i * 20, py, px + i * 20, py - 5, line_w, layer_h, filament_dia, print_speed, 0);
    }
    emit_footer(f, 0, travel_speed, &e); fclose(f); return true;
}

bool calib_speed(const char *path, float bed_temp, int nozzle_temp, float layer_h,
                 float line_w, float print_speed, float travel_speed, float filament_dia,
                 float speed_min, float speed_max, float speed_step) {
    if (!path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    emit_header(f, bed_temp, nozzle_temp, "Speed Test");
    float e = 0, z = layer_h;
    fprintf(f, "G1 Z%.3f F%.0f\n", z, travel_speed * 60);
    float px = 50, py = 100;
    int n = (int)((speed_max - speed_min) / speed_step) + 1;
    for (int i = 0; i < n; i++) {
        float spd = speed_min + i * speed_step;
        float ly = py - i * 8;
        g92_reset(f); e = 0;
        travel(f, &e, px, ly, 0, travel_speed);
        unretract(f, &e, 0, spd);
        extruder_move(f, &e, px + 80, ly, px, ly, line_w, layer_h, filament_dia, spd, 1);
    }
    emit_footer(f, 0, travel_speed, &e); fclose(f); return true;
}
