#include "gcode.h"
#include "../core/util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979
#endif

int gcode_pick_tool(const SliceSettings *cfg) {
    if (!cfg || cfg->tools <= 0 || !cfg->random_color) return -1;
    return rand() % cfg->tools;
}

static int pick_tool(const SliceSettings *cfg, int forced) {
    if (forced >= 0 && forced < cfg->tools) return forced;
    return gcode_pick_tool(cfg);
}

bool gcode_emit_fp_tool(FILE *f, SliceResult *r, const SliceSettings *cfg, int forced_tool) {
    if (!f || !r || !cfg) return false;
    float cross = (float)(M_PI * (cfg->filament_dia / 2.0) * (cfg->filament_dia / 2.0));
    if (cross < 1e-6f) cross = 1.0f;

    fprintf(f, "; generated by Volt360 slicer (Orca-style)\n");
    fprintf(f, "; printer: %s\n", cfg->printer_name ? cfg->printer_name : "unknown");
    fprintf(f, "; layers: %d layer_height: %.2f filament: %.1f mm est_time: %.1f s\n",
            r->nlayers, cfg->layer_height, r->filament_mm, r->est_time_s);
    fprintf(f, "M140 S%d\n", cfg->bed_temp);
    fprintf(f, "M190 S%d\n", cfg->bed_temp);
    fprintf(f, "M104 S%d\n", cfg->hotend_temp);
    fprintf(f, "M109 S%d\n", cfg->hotend_temp);
    fprintf(f, "G28 ; home all axes\n");

    int tool = pick_tool(cfg, forced_tool);
    if (tool >= 0) fprintf(f, "T%d ; AMS/CFS slot%s\n", tool, forced_tool >= 0 ? " (mapped)" : " (random color)");
    if (cfg->start_gcode) fprintf(f, "%s\n", cfg->start_gcode);

    double e = 0;
    int current_temp = cfg->hotend_temp;
    for (int li = 0; li < r->nlayers; li++) {
        SliceLayer *L = &r->layers[li];
        if (cfg->color_change_layer >= 0 && li == cfg->color_change_layer)
            fprintf(f, "%s ; color change at layer %d\n", cfg->color_change_cmd ? cfg->color_change_cmd : "M600", li);
        if (L->npaths <= 0) continue;
        fprintf(f, ";LAYER:%d ;Z:%.2f\n", li, L->z);
        fprintf(f, "G1 Z%.2f F%.0f ; move to layer\n", L->z, cfg->travel_speed * 60.0);
        int started = 0;
        for (int j = 0; j < L->npaths; j++) {
            SlicePath *p = &L->paths[j];
            if (p->npts < 2) continue;
            // per-feature overrides
            float eff_h = cfg->layer_height;
            float speed = cfg->print_speed;
            int want_temp = cfg->hotend_temp;
            if (p->kind == SLICE_PATH_PERIMETER) {
                if (cfg->wall_speed_mult > 0) speed = cfg->print_speed * cfg->wall_speed_mult;
                if (cfg->wall_layer_height > 0) eff_h = cfg->wall_layer_height;
                if (cfg->wall_temp > 0) want_temp = cfg->wall_temp;
            } else if (p->solid) {
                if (cfg->solid_speed_mult > 0) speed = cfg->print_speed * cfg->solid_speed_mult;
                if (cfg->infill_temp > 0) want_temp = cfg->infill_temp;
            } else {
                if (cfg->infill_speed_mult > 0) speed = cfg->print_speed * cfg->infill_speed_mult;
                if (cfg->infill_temp > 0) want_temp = cfg->infill_temp;
            }
            if (want_temp != current_temp) {
                fprintf(f, "M104 S%d ; feature temp\n", want_temp);
                current_temp = want_temp;
            }
            V2 s0 = p->pts[0];
            if (!started) {
                started = 1;
                fprintf(f, "G92 E0 ; reset extruder at layer start\n");
            }
            if (e > 0.01) {
                fprintf(f, "G1 E-%.3f F%.0f ; retract\n", cfg->retract_mm, cfg->travel_speed * 60.0);
                e -= cfg->retract_mm;
            }
            fprintf(f, "G0 X%.3f Y%.3f F%.0f ; travel\n", s0.x, s0.y, cfg->travel_speed * 60.0);
            if (cfg->retract_mm > 0) {
                fprintf(f, "G1 E+%.3f F%.0f ; unretract\n", cfg->retract_mm, speed * 60.0);
                e += cfg->retract_mm;
            }
            fprintf(f, ";%s\n", p->kind == SLICE_PATH_PERIMETER ? "perimeter" : (p->solid ? "infill-solid" : "infill"));
            for (int k = 1; k < p->npts; k++) {
                V2 prev = p->pts[k - 1], v = p->pts[k];
                double Ld = v2_dist(prev, v);
                double vol = Ld * p->width * eff_h;
                double de = vol / cross * cfg->extrusion_mult;
                e += de;
                fprintf(f, "G1 X%.3f Y%.3f E%.4f F%.0f\n", v.x, v.y, e, speed * 60.0);
            }
        }
    }

    fprintf(f, "M104 S0 ; hotend off\n");
    fprintf(f, "M140 S0 ; bed off\n");
    if (cfg->farm_mode && cfg->auto_eject) {
        if (cfg->eject_gcode && cfg->eject_gcode[0]) {
            fprintf(f, "; custom removal gcode\n%s\n", cfg->eject_gcode);
        } else {
            fprintf(f, "; auto-eject sequence (release temp %dC)\n", cfg->eject_release_temp);
            if (cfg->eject_release_temp > 0)
                fprintf(f, "M190 S%d ; wait for bed cool to release temp\n", cfg->eject_release_temp);
            fprintf(f, "M300 S440 P100 ; alert\n");
            fprintf(f, "M280 P0 S%d ; servo eject\n", (int)cfg->eject_angle);
            fprintf(f, "G1 X0 Y0 F3000 ; park\n");
        }
    }
    fprintf(f, "M84 ; motors off\n");
    if (cfg->end_gcode) fprintf(f, "%s\n", cfg->end_gcode);
    fprintf(f, "; llc end\n");
    return true;
}

bool gcode_emit_fp(FILE *f, SliceResult *r, const SliceSettings *cfg) {
    return gcode_emit_fp_tool(f, r, cfg, cfg ? cfg->forced_tool : -1);
}

bool gcode_emit(SliceResult *r, const SliceSettings *cfg, const char *path) {
    if (!path) return false;
    FILE *f = fopen(path, "w");
    if (!f) return false;
    bool ok = gcode_emit_fp(f, r, cfg);
    fclose(f);
    return ok;
}
