#include "gerber_out.h"
#include "../core/util.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

static void gerb_header(FILE *f) {
    fprintf(f, "%%FSLAX34Y34*%%\n%%MOMM*%%\n%%ADD10C,0.15*%%\n%%ADD11C,0.30*%%\n%%ADD12C,0.50*%%\n");
    fprintf(f, "G04 Gerber generated by Volt360 *\n");
    fprintf(f, "%%LPD*%%\n");
}

static void gerb_footer(FILE *f) { fprintf(f, "M02*\n"); }

static void gerb_move(FILE *f, float x, float y) { fprintf(f, "X%.3fY%.3fD02*\n", x, y); }
static void gerb_draw(FILE *f, float x, float y) { fprintf(f, "X%.3fY%.3fD01*\n", x, y); }
static void gerb_flash(FILE *f, float x, float y, int ap) { fprintf(f, "X%.3fY%.3fD03*\n", x, y); }
static void gerb_select(FILE *f, int ap) { fprintf(f, "D%d*\n", ap + 10); }

bool gerber_write_copper(Pcb *pcb, const char *path, const char *layer_name) {
    if (!pcb || !path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    gerb_header(f);
    fprintf(f, "G04 Layer: %s *\n", layer_name ? layer_name : "?");
    // tracks
    gerb_select(f, 0);
    for (int i = 0; i < pcb->ntracks; i++) {
        gerb_move(f, pcb->tracks[i].a.x, pcb->tracks[i].a.y);
        gerb_draw(f, pcb->tracks[i].b.x, pcb->tracks[i].b.y);
    }
    // pads as flashes
    gerb_select(f, 1);
    for (int i = 0; i < pcb->nfps; i++) {
        gerb_flash(f, pcb->fps[i].pos.x, pcb->fps[i].pos.y, 1);
    }
    gerb_footer(f); fclose(f); return true;
}

bool gerber_write_outline(Pcb *pcb, const char *path) {
    if (!pcb || !path || pcb->noutline < 3) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    gerb_header(f);
    fprintf(f, "G04 Board Outline *\n");
    gerb_select(f, 2);
    gerb_move(f, pcb->outline[0].x, pcb->outline[0].y);
    for (int i = 1; i < pcb->noutline; i++) gerb_draw(f, pcb->outline[i].x, pcb->outline[i].y);
    gerb_draw(f, pcb->outline[0].x, pcb->outline[0].y); // close
    gerb_footer(f); fclose(f); return true;
}

bool gerber_write_drill(Pcb *pcb, const char *path) {
    if (!pcb || !path || pcb->nvias <= 0) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    fprintf(f, "M48\n; Excellon drill file (generated by Volt360)\n");
    fprintf(f, "%%T01C%.3f\n", pcb->vias[0].drill > 0 ? pcb->vias[0].drill : 0.8f);
    for (int i = 0; i < pcb->nvias; i++)
        fprintf(f, "X%.3fY%.3f\n", pcb->vias[i].pos.x, pcb->vias[i].pos.y);
    fprintf(f, "M30\n");
    fclose(f); return true;
}

bool gerber_write_all(Pcb *pcb, const char *dir) {
    if (!pcb || !dir) return false;
    char path[512];
    snprintf(path, sizeof(path), "%s/%s-F_Cu.gbr", dir, pcb->name ? pcb->name : "board");
    gerber_write_copper(pcb, path, "F_Cu");
    snprintf(path, sizeof(path), "%s/%s-Edge_Cuts.gbr", dir, pcb->name ? pcb->name : "board");
    gerber_write_outline(pcb, path);
    snprintf(path, sizeof(path), "%s/%s.drl", dir, pcb->name ? pcb->name : "board");
    gerber_write_drill(pcb, path);
    return true;
}
