#include "mfg_out.h"
#include "gerber_out.h"
#include "../core/util.h"
#include <stdio.h>
#include <string.h>

bool mfg_pickplace(Pcb *pcb, const char *path) {
    if (!pcb || !path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    fprintf(f, "Ref,Value,Package,PosX,PosY,Rotation,Side\n");
    for (int i = 0; i < pcb->nfps; i++) {
        FpInst *fp = &pcb->fps[i];
        fprintf(f, "%s,%s,%s,%.3f,%.3f,%.0f,%s\n",
            fp->ref ? fp->ref : "?",
            fp->value ? fp->value : "",
            fp->footprint ? fp->footprint : "?",
            fp->pos.x, fp->pos.y, fp->rotation,
            fp->side == 0 ? "Top" : "Bottom");
    }
    fclose(f); return true;
}

bool mfg_ipc356(Pcb *pcb, const char *path) {
    if (!pcb || !path) return false;
    FILE *f = fopen(path, "w"); if (!f) return false;
    fprintf(f, "C  IPC-356 netlist  (generated by Volt360)\n");
    fprintf(f, "C  Board: %s\n", pcb->name ? pcb->name : "?");
    for (int i = 0; i < pcb->nfps; i++)
        fprintf(f, "327%s  D%.0fPA00X%+.4fY%+.4fX0600Y\n",
            pcb->fps[i].ref ? pcb->fps[i].ref : "?",
            pcb->fps[i].rotation,
            pcb->fps[i].pos.x, pcb->fps[i].pos.y);
    fprintf(f, "999\n");
    fclose(f); return true;
}

bool mfg_odbpp(Pcb *pcb, const char *dir) {
    if (!pcb || !dir) return false;
    char path[512];
    snprintf(path, sizeof(path), "%s/steps/pcb/odb_profile", dir);
    FILE *f = fopen(path, "w");
    if (f) { fprintf(f, "# ODB++ stub\n# Board: %s\n", pcb->name ? pcb->name : "?"); fclose(f); }
    return true;
}

bool mfg_export_all(Pcb *pcb, const char *dir) {
    if (!pcb || !dir) return false;
    char path[512];
    snprintf(path, sizeof(path), "%s/%s-pnp.csv", dir, pcb->name ? pcb->name : "board");
    mfg_pickplace(pcb, path);
    snprintf(path, sizeof(path), "%s/%s-ipc356.net", dir, pcb->name ? pcb->name : "board");
    mfg_ipc356(pcb, path);
    gerber_write_all(pcb, dir);
    return true;
}
